from enum import Enum


class PurchaseStatus(Enum):
    BEING_MADE ="EM_PREPARO"
    DELIVERED = "ENTREGUE"
    MADE = "FEITO"
    OUT_TO_DELIVERY = "SAIU_PARA_ENTREGA"
    ACCEPTED = "ACEITO"
    WAITING_ACCEPTANCE = "AGUARDANDO_RESTAURANTE"
    CANCELED = "CANCELADO"
